#ifndef _WEBCONFIG_H
#define _WEBCONFIG_H

String webHTML = "<!DOCTYPE html><html lang=\"en-US\" encoding=\"UTF-16\"><head><title>Digital Oscilloscope</title><link rel=\"stylesheet\" href=\"styles.css\"><script src=\"main.js\" defer></script></head><body><section class=\"mainContent\"><div class=\"header\"><br><h4>Proyectos Experimentales II</h4><h1>OSCILOSCOPIO DIGITAL</h1><br><hr></div><div class=\"oscMainBody\"><div class=\"oscValsLeft\">Units<br><div class=\"dataField\"><p style=\"display: inline-block\" id=\"Vpp\">Vpeak-peak: NaN</p><select class=\"dropDown\" onchange=\"update_vpp(event)\"><option>Vpp</option><option>mVpp</option></select></div><div class=\"dataField\"><p style=\"display: inline-block\" id=\"Vp\">Vpeak: NaN</p><select class=\"dropDown\" onchange=\"update_vp(event)\"><option>Vp</option><option>mVp</option></select></div><div class=\"dataField\"><p style=\"display: inline-block\" id=\"Freq\">Frequency: NaN</p><select class=\"dropDown\" onchange=\"update_freq(event)\"><option>Hz</option><option>kHz</option></select></div><div class=\"dataField\"><p style=\"display: inline-block\" id=\"Period\">Period: NaN</p><select class=\"dropDown\" onchange=\"update_period(event)\"><option>s</option><option>ms</option></select></div></div><div class=\"oscValsCenter\"><h1>SELECIONE LAS UNIDADES</h1></div><div class=\"oscValsRight\"><h1>M&AacuteSTER EN INGENIER&IacuteA DE SISTEMAS ELECTR&OacuteNICOS Y APLICACIONES</h1></div></div><footer class=\"footer\"><div><h6>&copy Javier L&aacutezaro Fern&aacutendez &amp; Julia Uruel Sanz - MISEA 2022</h6></div></footer></section></body></html>";
String webCSS = "* {font-family: 'Courier New', Courier, monospace;margin: 0;padding: 0;box-sizing: border-box;}hr {background-color: #D81E5B;color: #D81E5B;}.mainContent {background-color: #3A3335;}.header {align-items: center;text-align: center;color: #D81E5B;}.mainContent.header {align-items: center;text-align: center;color: #D81E5B;}.footer {color: #3A3335;align-items: center;text-align: center;background-color: #D81E5B;}.dropDown{margin-left: 5px;border: 1px solid #F0544F ;color: #F0544F;background-color: #3A3335;width: 5vw;height: 1.5rem;padding: 2px  2px  2px  2px;}.dataField{margin-bottom: 10px;}.dataField p span{color: #fdf0d5;}.oscMainBody{display: flex;flex-direction: row;}.oscValsLeft {color: #F0544F;width: fit-content;margin-left: 10px;padding-top: 10px;padding-bottom: 10px;text-align: right;flex-shrink: 0;}.oscValsCenter{color: #fdf0d5;width: fit-content;margin-left: 100px;padding-top: 10px;padding-bottom: 10px;text-align: center;}.oscValsRight{color: #F0544F;width: fit-content;margin-left: 100px;padding-top: 10px;padding-bottom: 10px;text-align: center;}";
String webJs = "let vpp_units = document.querySelector(\"#Vpp\");function update_vpp(event){fetch(\"/vpp_units\").then((response)=>{return response.text();}).then((data)=>{let vpp_val = parseInt(data);if(event.target.value === \"Vpp\"){vpp_val = vpp_val/1000;}vpp_units.innerHTML = `Vpeak-peak: <span>${vpp_val} </span>`;});}let vp_units = document.querySelector(\"#Vp\");function update_vp(event){fetch(\"/vp_units\").then((response)=>{return response.text();}).then((data)=>{let vp_val = parseInt(data);if(event.target.value === \"Vp\"){vp_val = vp_val/1000;}vp_units.innerHTML = `Vpeak: <span>${vp_val} </span>`;});}let freq_units = document.querySelector(\"#Freq\");function update_freq(event){fetch(\"/freq_units\").then((response)=>{return response.text();}).then((data)=>{let freq_val = parseInt(data);if(event.target.value === \"kHz\"){freq_val = freq_val/1000;}freq_units.innerHTML = `Frequency: <span>${freq_val} </span>`;});}let period_units = document.querySelector(\"#Period\");function update_period(event){fetch(\"/period_units\").then((response)=>{return response.text();}).then((data)=>{let period_val = parseInt(data);if(event.target.value === \"s\"){period_val = period_val/1000;}period_units.innerHTML = `Period: <span>${period_val} </span>`;});}";



#endif
